#
# Copyright (c) 2025, Focus-5 Consortium Members
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: analysis-requester_config
  labels:
    app: analysis-requester_config
data:
  requester-opal-proxy_host: "localhost"
  requester-opal-proxy_port: "9443"
