#
# Copyright (c) 2025, Focus-5 Consortium Members
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: analysis-requester-config
  labels:
    app: analysis-requester-config
data:
  requester-opal-proxy-host: "localhost"
  requester-opal-proxy-port: "9443"
